FROM node:18-alpine

WORKDIR /app

# Copy package.json and package-lock.json
COPY package.json ./

# Install dependencies
RUN npm install

# Copy the rest of the code
COPY server.js ./

# Expose port for server
EXPOSE 3001

# Start the server
CMD ["node", "server.js"] 